### ISSUE TITLE
ClassCastException: GrLiteralImpl cannot be cast to PsiLiteralExpression

### ISSUE THREAD

**Issue by joshcanfield** [ishchenko/idea-mini-ibatis#8]
Intellij 12.1.2

```
org.jetbrains.plugins.groovy.lang.psi.impl.statements.expressions.literals.GrLiteralImpl cannot be cast to com.intellij.psi.PsiLiteralExpression: org.jetbrains.plugins.groovy.lang.psi.impl.statements.expressions.literals.GrLiteralImpl cannot be cast to com.intellij.psi.PsiLiteralExpression
java.lang.ClassCastException: org.jetbrains.plugins.groovy.lang.psi.impl.statements.expressions.literals.GrLiteralImpl cannot be cast to com.intellij.psi.PsiLiteralExpression
    at net.ishchenko.idea.minibatis.MyBatisReferenceContributor$1.getReferencesByElement(MyBatisReferenceContributor.java:22)
    at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.doGetReferencesFromProviders(ReferenceProvidersRegistryImpl.java:119)
    at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:65)
    at org.jetbrains.plugins.groovy.lang.psi.impl.statements.expressions.literals.GrLiteralImpl.getReferences(GrLiteralImpl.java:157)
    at com.intellij.psi.PsiReferenceServiceImpl.getReferences(PsiReferenceServiceImpl.java:34)
    at com.intellij.psi.search.SingleTargetRequestResultProcessor.processTextOccurrence(SingleTargetRequestResultProcessor.java:40)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$20.execute(PsiSearchHelperImpl.java:681)
    at com.intellij.psi.impl.search.LowLevelSearchUtil.a(LowLevelSearchUtil.java:123)
    at com.intellij.psi.impl.search.LowLevelSearchUtil.processElementsContainingWordInElement(LowLevelSearchUtil.java:171)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$5.process(PsiSearchHelperImpl.java:204)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$5.process(PsiSearchHelperImpl.java:201)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$7$2.run(PsiSearchHelperImpl.java:251)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:929)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$7.process(PsiSearchHelperImpl.java:238)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$7.process(PsiSearchHelperImpl.java:227)
    at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:105)
    at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgressAsync(JobLauncherImpl.java:131)
    at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgressAsync(JobLauncherImpl.java:37)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl.a(PsiSearchHelperImpl.java:227)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl.a(PsiSearchHelperImpl.java:201)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl.processElementsWithWordAsync(PsiSearchHelperImpl.java:138)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl.c(PsiSearchHelperImpl.java:834)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl.a(PsiSearchHelperImpl.java:602)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl.access$400(PsiSearchHelperImpl.java:55)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$17.body(PsiSearchHelperImpl.java:530)
    at com.intellij.concurrency.DoWhile.getResult(DoWhile.java:32)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl.processRequestsAsync(PsiSearchHelperImpl.java:574)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl.processRequests(PsiSearchHelperImpl.java:510)
    at com.intellij.psi.search.SearchRequestQuery.processResults(SearchRequestQuery.java:29)
    at com.intellij.util.AbstractQuery.forEach(AbstractQuery.java:77)
    at com.intellij.util.MergeQuery.processSubQuery(MergeQuery.java:83)
    at com.intellij.util.MergeQuery.forEach(MergeQuery.java:56)
    at com.intellij.util.MergeQuery.findFirst(MergeQuery.java:50)
    at com.intellij.util.UniqueResultsQuery.findFirst(UniqueResultsQuery.java:51)
    at org.jetbrains.plugins.groovy.codeInspection.unusedDef.UnusedDefInspection$3.visitVariable(UnusedDefInspection.java:144)
    at org.jetbrains.plugins.groovy.lang.psi.GroovyElementVisitor.visitParameter(GroovyElementVisitor.java:336)
    at org.jetbrains.plugins.groovy.lang.psi.impl.statements.params.GrParameterImpl.accept(GrParameterImpl.java:70)
    at org.jetbrains.plugins.groovy.lang.psi.impl.GroovyPsiElementImpl.acceptGroovyChildren(GroovyPsiElementImpl.java:75)
    at org.jetbrains.plugins.groovy.lang.psi.impl.GrStubElementBase.acceptChildren(GrStubElementBase.java:55)
    at org.jetbrains.plugins.groovy.lang.psi.GroovyRecursiveElementVisitor.visitElement(GroovyRecursiveElementVisitor.java:24)
    at org.jetbrains.plugins.groovy.lang.psi.GroovyElementVisitor.visitParameterList(GroovyElementVisitor.java:332)
    at org.jetbrains.plugins.groovy.lang.psi.impl.statements.params.GrParameterListImpl.accept(GrParameterListImpl.java:55)
    at org.jetbrains.plugins.groovy.lang.psi.impl.GroovyPsiElementImpl.acceptGroovyChildren(GroovyPsiElementImpl.java:75)
    at org.jetbrains.plugins.groovy.lang.psi.impl.GrStubElementBase.acceptChildren(GrStubElementBase.java:55)
    at org.jetbrains.plugins.groovy.lang.psi.GroovyRecursiveElementVisitor.visitElement(GroovyRecursiveElementVisitor.java:24)
    at org.jetbrains.plugins.groovy.lang.psi.GroovyElementVisitor.visitMethod(GroovyElementVisitor.java:288)
    at org.jetbrains.plugins.groovy.lang.psi.impl.statements.typedef.members.GrMethodBaseImpl.accept(GrMethodBaseImpl.java:104)
    at org.jetbrains.plugins.groovy.lang.psi.impl.GroovyPsiElementImpl.acceptGroovyChildren(GroovyPsiElementImpl.java:75)
    at org.jetbrains.plugins.groovy.lang.psi.impl.GrStubElementBase.acceptChildren(GrStubElementBase.java:55)
    at org.jetbrains.plugins.groovy.lang.psi.GroovyRecursiveElementVisitor.visitElement(GroovyRecursiveElementVisitor.java:24)
    at org.jetbrains.plugins.groovy.lang.psi.GroovyElementVisitor.visitTypeDefinitionBody(GroovyElementVisitor.java:344)
    at org.jetbrains.plugins.groovy.lang.psi.impl.statements.typedef.GrTypeDefinitionBodyBase$GrClassBody.accept(GrTypeDefinitionBodyBase.java:171)
    at org.jetbrains.plugins.groovy.lang.psi.impl.GroovyPsiElementImpl.acceptGroovyChildren(GroovyPsiElementImpl.java:75)
    at org.jetbrains.plugins.groovy.lang.psi.impl.GrStubElementBase.acceptChildren(GrStubElementBase.java:55)
    at org.jetbrains.plugins.groovy.lang.psi.GroovyRecursiveElementVisitor.visitElement(GroovyRecursiveElementVisitor.java:24)
    at org.jetbrains.plugins.groovy.lang.psi.GroovyElementVisitor.visitTypeDefinition(GroovyElementVisitor.java:260)
    at org.jetbrains.plugins.groovy.lang.psi.impl.statements.typedef.GrTypeDefinitionImpl.accept(GrTypeDefinitionImpl.java:117)
    at org.jetbrains.plugins.groovy.lang.psi.impl.GroovyFileBaseImpl.acceptChildren(GroovyFileBaseImpl.java:225)
    at org.jetbrains.plugins.groovy.lang.psi.GroovyRecursiveElementVisitor.visitElement(GroovyRecursiveElementVisitor.java:24)
    at org.jetbrains.plugins.groovy.lang.psi.GroovyElementVisitor.visitFile(GroovyElementVisitor.java:64)
    at org.jetbrains.plugins.groovy.lang.psi.impl.GroovyFileBaseImpl.accept(GroovyFileBaseImpl.java:218)
    at org.jetbrains.plugins.groovy.codeInspection.unusedDef.UnusedDefInspection.check(UnusedDefInspection.java:139)
    at org.jetbrains.plugins.groovy.codeInspection.GroovyLocalInspectionBase$1.visitFile(GroovyLocalInspectionBase.java:56)
    at org.jetbrains.plugins.groovy.lang.psi.impl.GroovyFileBaseImpl.accept(GroovyFileBaseImpl.java:218)
    at org.jetbrains.plugins.groovy.lang.psi.GroovyPsiElementVisitor.visitElement(GroovyPsiElementVisitor.java:33)
    at com.intellij.psi.PsiElementVisitor.visitFile(PsiElementVisitor.java:32)
    at com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:70)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:412)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.access$300(LocalInspectionsPass.java:78)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$4.process(LocalInspectionsPass.java:388)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$4.process(LocalInspectionsPass.java:382)
    at com.intellij.concurrency.JobLauncherImpl$2$1.run(JobLauncherImpl.java:115)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:226)
    at com.intellij.concurrency.JobLauncherImpl$2.process(JobLauncherImpl.java:113)
    at com.intellij.concurrency.JobLauncherImpl$1.run(JobLauncherImpl.java:54)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at com.intellij.concurrency.PrioritizedFutureTask.access$101(PrioritizedFutureTask.java:31)
    at com.intellij.concurrency.PrioritizedFutureTask$1.run(PrioritizedFutureTask.java:70)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1182)
    at com.intellij.concurrency.PrioritizedFutureTask.run(PrioritizedFutureTask.java:97)
    at com.intellij.concurrency.JobImpl.scheduleAndWaitForResults(JobImpl.java:136)
    at com.intellij.concurrency.JobLauncherImpl.a(JobLauncherImpl.java:68)
    at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:110)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:398)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:220)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:136)
    at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:58)
    at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:62)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:357)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1182)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:348)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:226)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:345)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:321)
    at com.intellij.concurrency.JobLauncherImpl$3.call(JobLauncherImpl.java:145)
    at com.intellij.concurrency.JobLauncherImpl$3.call(JobLauncherImpl.java:142)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at com.intellij.concurrency.PrioritizedFutureTask.access$101(PrioritizedFutureTask.java:31)
    at com.intellij.concurrency.PrioritizedFutureTask$1.run(PrioritizedFutureTask.java:70)
    at com.intellij.concurrency.PrioritizedFutureTask.run(PrioritizedFutureTask.java:113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
    at java.lang.Thread.run(Thread.java:680)
```

**Comment by ishchenko** [comment]
It appears that Groovy string literals would match with PsiJavaPatterns.psiLiteral(), but they are not PsiLiteralExpression instances. I should cast to PsiLiteral instance that would work in Groovy as well.

**Comment by ishchenko** [comment]
Fixed in https://github.com/ishchenko/idea-mini-ibatis/commit/0ea820ab2fc3c7e0b50d758e4e8aff90e38e1d3a

**Comment by joshcanfield** [comment]
Awesome, no more exceptions. Thanks for the quick turn around.
